package by.epam.bohnat.provider.command;

/**
 * An enumeration that contains all existing command names.
 * 
 * @author Denis Bohnat
 * @version 1.0
 */
public enum CommandName {

	ABOUT_US,
	ADD_TARIFF,
	ADD_USER,
	ADDING_TARIFF,
	BAN_USER,
	BRING_MONTHLY_FEE,
	BUY_TARIFF,
	CANCEL,
	CHANGE_LANGUAGE,
	CHANGE_TARIFF_PLAN,
	DELETE_REQUEST,
	DELETE_TARIFF,
	DELETE_USER,
	EDIT_PROFILE,
	EDIT_TARIFF,
	EDITING_TARIFF,
	HOME,
	LIMITED_TARIFFS,
	LOGIN,
	LOGOUT,
	OPEN_ADD_USER_PAGE,
	OPEN_ALL_NON_PAYERS_PAGE,
	OPEN_ALL_REQUESTS_PAGE,
	OPEN_PROFILE,
	OPEN_SIGN_UP_PAGE,
	OPEN_START_PAGE,
	OPEN_USER_ACCOUNT_PAGE,
	OPEN_USER_DETAILS_PAGE,
	OPEN_USER_FEE_PAGE,
	OPEN_USER_PAYMENT_PAGE,
	OPEN_USER_REQUEST_PAGE,
	SEND_REQUEST,
	SHOW_ADMINS,
	SHOW_CUSTOMERS,
	SHOW_TARIFFS,
	SIGN_UP,
	TERMINATE_ACCOUNT,
	UNLIMITED_TARIFFS
}
